wip: implement TableServiceUpdater
agrc/palletjack pull request #101
Opened 2024-08-02 20:20 UTC by stdavis

There is still a lot of duplicate code that could be extracted to a base class for both FeatureServiceUpdater and TableServiceUpdater. But this does work as is for the deq-eid skid.

@jacobadams - I'm interested to see what you think and your thoughts on where this needs to go from here.

2024-08-06 23:54 UTC, jacobdadams reviewed
Thanks for tackling this feature. I think you're headed in the right direction. There are a couple places where the table code still references methods in FeatureServiceUpdater, but I'm assuming you'll tackle that after figuring out the DRY stuff. 

For drying it up (I'm totally stealing that phrase), just thinking off the cuff, I wonder if we don't do a base ServiceUpdater class and then have the two different types inherit from that. If the method calls are named the same between the ArcGIS Feature Service and Table Service objects, maybe the base class has a property that is the service object and then the children just create the requisite type of object? 

Otherwise, if we want to avoid inheritance... we could make methods that take in the proper object type and then perform the actions... which is really similar to the base class idea... Not sure if I can come up with something different right now.

2024-08-06 23:54 UTC, jacobdadams commented on src/palletjack/load.py
> +    def update_rows(self, dataframe, update_geometry=True):
We don't need the `update_geometry` steps anymore since we're only working with the table.

2024-08-07 14:04 UTC, stdavis commented
Thanks for the review. I think that I'll try the base class solution first and see how it goes.

2024-08-08 23:56 UTC, stdavis commented
@jacobdadams I'd love another general look at this. After DRYing up the differences between `FeatureServiceUpdater` and `TableServiceUpdater`, there was almost nothing left in the subclasses. So I just got rid of them in favor of a generic `ServiceUpdater` class that has a slightly different api. This would be a breaking change. If you are good with this direction, I'll finish updating the docs and make sure that the test converage is good.

2024-08-09 17:38 UTC, jacobdadams commented
Impressive! I'm all for it. I think it makes a ton of sense to generalize it. palletjack has already got a history of breaking changes, so I'm not too worried and this should be a relatively simple fix for scripts we want to update. 

And no worries about "going off the rails"- I'm grateful you took this improvement on and are making it better. I think this is becoming the standard development model for palletjack- desired features are added when we've got funding in a project that needs them. I'm all for a standard, unified codebase that we can all use.

2024-08-09 22:22 UTC, stdavis commented
@jacobdadams This is ready for a serious look now. I went back and forth on the method renames. If you want to minimize the breaking changes, I'm happy to switch them back. The `_features` suffix seemed weird to me if you are working with a table. However, I noticed that the [`arcgis` package does it](https://developers.arcgis.com/python/api-reference/arcgis.features.toc.html#table) so maybe it's not a big deal.

Here's what my functional test code looks like:
```python
incidents_sdf = self._get_incidents()
incidents_loader = load.ServiceUpdater(
    self.gis,
    config.INCIDENTS_ITEMID,
    working_dir=self.tempdir_path,
)

#: testing only
incidents_add_count = incidents_loader.add(incidents_sdf[0:10])
incidents_remove_count = incidents_loader.remove([1, 2, 3])
incidents_live_sdf = (
    arcgis.features.FeatureLayer.fromitem(self.gis.content.get(config.INCIDENTS_ITEMID)).query().sdf
)
incidents_live_sdf = incidents_live_sdf[-10:]
incidents_live_sdf["Title_EventName"] = "Test Title Change"
incidents_live_sdf.drop(columns=["Date_Discovered_For_Filter"], inplace=True)
incidents_update_count = incidents_loader.update(incidents_live_sdf)

incidents_count = incidents_loader.truncate_and_load(incidents_sdf)

chemical_df = self._get_chemical()
chemical_loader = load.ServiceUpdater(
    self.gis,
    config.CHEMICAL_ITEMID,
    service_type="table",
    working_dir=self.tempdir_path,
)

#: testing only
chemical_add_count = chemical_loader.add(chemical_df[0:10])
chemical_remove_count = chemical_loader.remove([1, 2, 3])
chemical_live_df = arcgis.features.Table.fromitem(self.gis.content.get(config.CHEMICAL_ITEMID)).query().sdf
chemical_live_df = chemical_live_df[-10:]
chemical_live_df["Chemical_Name"] = "Test Name Change"
chemical_update_count = chemical_loader.update(chemical_live_df)

chemical_count = chemical_loader.truncate_and_load(chemical_df)

media_df = self._get_media()
media_loader = load.ServiceUpdater(
    self.gis,
    config.MEDIA_ITEMID,
    service_type="table",
    working_dir=self.tempdir_path,
)
media_count = media_loader.truncate_and_load(media_df)
```

It might be cool to add some functional tests to this project that actually update dedicated test items in AGOL. Maybe not great to run in an automated way, but it might be a nice sanity check to see if everything works together. Just an idea.

2024-08-12 20:00 UTC, jacobdadams requested changes
Nice and clean, I like it! Thanks for updating the tests and generalizing everything.

One request: I noticed you moved the types from the docstrings to the signatures for full type hinting. I love the type hinting, but `pdoc3` relies on having the type info as part of the docstring, and all the other classes/modules follow this pattern. Could you please restore the types to the docstrings in addition to the method signatures?

2024-08-12 20:00 UTC, jacobdadams commented on .github/workflows/pull_request.yml
Shouldn't this be swapped with push.yml, so it does all the tests on each push and the releases on PRs instead of the other way around?

2024-08-12 20:00 UTC, jacobdadams commented on docs/README.md
> +| v4                       | v5                |
Love the tables!

2024-08-12 20:00 UTC, jacobdadams commented on tests/test_load.py
> +        updater_mock = mocker.Mock(spec=load.ServiceUpdater)
For my own curiosity, was there a specific reason beyond general good practice to spec this mock? I'm curious if I've been missing something by not spec'ing.

2024-08-12 20:21 UTC, steveoh commented on tests/test_load.py
> +        updater_mock = mocker.Mock(spec=load.ServiceUpdater)
spec lets you define the shape of the mock. Without the spec, method calls on the mock that don't exist succeed.

2024-08-13 18:36 UTC, stdavis commented on tests/test_load.py
> +        updater_mock = mocker.Mock(spec=load.ServiceUpdater)
I started adding this after seeing some tests fail because of missing class methods.

2024-08-13 18:40 UTC, stdavis commented on .github/workflows/pull_request.yml
No, I don't believe so. This will trigger the tests when a PR is opened or when a new commit is added to a PR. Assuming that all changes go through a PR, this means that everything should be tested. `push.yml` works when changes are merged to `dev` or `main` and is responsible only for releasing. The tests are also run again for each release PR.

Previous to my changes to the actions in this repo, the tests were being run twice for each push to a PR in duplicate.

2024-08-13 18:42 UTC, stdavis commented
> One request: I noticed you moved the types from the docstrings to the signatures for full type hinting. I love the type hinting, but `pdoc3` relies on having the type info as part of the docstring, and all the other classes/modules follow this pattern. Could you please restore the types to the docstrings in addition to the method signatures?

Ah, that's why you had them duplicated. It's a shame that their can't be a single source of truth for them. I did find one instance where there was a discrepancy between the docstrings and the type hinting. I'll add them back...

2024-08-13 19:00 UTC, stdavis commented
@jacobdadams I added the types back to the docstrings. Let me know if there is anything else that I can do. Thanks for the review!

2024-08-14 16:25 UTC, jacobdadams commented on .github/workflows/pull_request.yml
Ok, I think I see my confusion- it creates a release, but doesn't push to pypi- that's a separate step in `release.yml`... that gets triggered every release, so it seems like we're publishing to pypi on every push?

Do we have any docs on the release action- what branch name structure to use, which commit flags trigger different version bumps? 

I've been using the pattern of doing work in `dev` and then PR'ing that to `main`, but it looks like this creates a release and pushes to pypi at every push to dev, which I don't want to do under my current pattern. Should I be doing a `feat/something` branch that then gets merged into dev for a pre-release and then that gets merged into main? 

I need a little more training on how this all works before I feel confident that I won't screw things up.

2024-08-14 20:39 UTC, jacobdadams commented on .github/workflows/pull_request.yml
Thanks for taking a moment to explain it all to me! 

My only concern is how the release bumper handles the fact that palletjack doesn't store its version in setup.py. The existing release action will update the version.py file, but I don't know if the other stuff will error out with palletjack's setup.py

2024-08-15 15:40 UTC, stdavis commented on .github/workflows/pull_request.yml
[d223b13](https://github.com/agrc/palletjack/pull/101/commits/d223b134a84296ad8580f8804f21dd913bc867b5) helps address this. But we won't know for sure until this is merged and a release PR is created. Once that happens, I'll submit a PR if necessary to fix anything before the release PR is merged.

2024-08-15 20:51 UTC, merged