feat: use Google API to download files
agrc/palletjack pull request #21
Opened 2022-09-01 17:22 UTC by jacobdadams

Use the Google API to download files instead of anonymous HTTP requests (but still leave the old code... will probably deprecate in v3). 

Google will block your anonymous requests after a certain amount of time, so this provides a more reliable way to download files.

2022-09-01 17:36 UTC, steveoh requested changes
Once the service account piece is sorted out I will approve this.

2022-09-01 17:36 UTC, steveoh commented on src/palletjack/loaders.py
> +        client = pygsheets.authorize(service_file=service_file)
**issue**: The service account file should be optional and the client created if it is used. The goal is for this to run in the cloud where the environment variables will authorize the client and the code will execute as the identity that has access. The current way is not compatible with the deployment hosting.

2022-09-02 01:43 UTC, jacobdadams commented on src/palletjack/loaders.py
> +        client = pygsheets.authorize(service_file=service_file)
Ok, I think I've got this sorted out. Take a look and let me know what you think.

2022-09-02 19:49 UTC, jacobdadams commented
Will also close #11

2022-09-06 17:19 UTC, steveoh commented on src/palletjack/loaders.py
> +        client = utils.authorize_pygsheets(credentials)
**suggestion**: I noticed another loader class takes the credentials in the ctor and creates a class client. It's nice to have consistency between classes for the sake of the api.

2022-09-06 17:21 UTC, steveoh approved these changes

2022-09-07 14:24 UTC, jacobdadams commented on src/palletjack/loaders.py
> +        client = utils.authorize_pygsheets(credentials)
Yeah, I agree. This PR is an extension of an existing class, and it may have been better to just create a new class instead. I'll add this to the v3 list.

2022-09-07 14:26 UTC, merged