add salesforce loader
agrc/palletjack pull request #72
Opened 2023-10-24 00:52 UTC by steveoh

initial skeleton to get a review before polish and tests

2023-10-24 14:22 UTC, jacobdadams approved these changes
Looks good to me. TIL `string.Template`.

2023-11-08 14:15 UTC, stdavis approved these changes

2023-11-08 14:15 UTC, stdavis commented on src/palletjack/extract.py
> +        #: TODO: make sure all of these required fields have values
Did you want to take care of this before merging or is this something that you don't mind if it waits until later?

2023-11-08 16:05 UTC, steveoh commented on src/palletjack/extract.py
> +        #: TODO: make sure all of these required fields have values
I shouldn't leave any todo's. I'll address it. Thanks for paying attention :)

2023-11-08 16:09 UTC, steveoh commented on src/palletjack/extract.py
> +        #: TODO: make sure all of these required fields have values
Ok I'm actually going to ignore validation because of https://docs.python.org/2/glossary.html?highlight=EAFP#term-eafp

2023-11-08 16:54 UTC, jacobdadams requested changes
I like it, and the documentation looks pretty solid. It'd be nice to parameterize the timeouts in case they need to be tweaked in use.

2023-11-08 16:54 UTC, jacobdadams commented on src/palletjack/extract.py
> +            timeout=10,
timeout should be parameterized (also L1022)

2023-11-08 16:54 UTC, jacobdadams commented on src/palletjack/extract.py
> +        """Queries the Salesforce API and returns the results as a dict.
nitpick: returns dataframe, not dict

2023-11-08 16:54 UTC, jacobdadams commented on src/palletjack/extract.py
> +    To use this loader a connected app needs to be created in Salesforce which create the credentials.
praise: thanks for the tips on how to build the SOQL query

2023-11-08 19:40 UTC, steveoh commented
Ok @jacobdadams, can I get a fresh review?

2023-11-08 20:55 UTC, jacobdadams approved these changes
LGTM.

2023-11-08 21:01 UTC, merged